local methods = {
    computer={
        beep=false,
        getDeviceInfo=true,
        getProgramLocations=false,
        isRunning=true,
        start=false,
        stop=false
    },
    eeprom={
        get=true,
        getChecksum=true,
        getData=true,
        getDataSize=true,
        getLabel=true,
        getSize=true,
        makeReadonly=true,
        set=false,
        setData=false,
        setLabel=false
    },
    filesystem={
        close=true,
        exists=true,
        getLabel=true,
        isDirectory=true,
        isReadOnly=true,
        lastModified=true,
        list=false,
        makeDirectory=false,
        open=true,
        read=true,
        remove=false,
        rename=false,
        seek=true,
        setLabel=false,
        size=true,
        spaceTotal=true,
        spaceUsed=true,
        write=true
    },
    gpu={
        bind=false,
        copy=true,
        fill=true,
        get=true,
        getBackground=true,
        getDepth=true,
        getForeground=true,
        getPaletteColor=true,
        getResolution=true,
        getScreen=true,
        getViewport=true,
        maxDepth=true,
        maxResolution=true,
        set=true,
        setBackground=true,
        setDepth=false,
        setForeground=true,
        setPaletteColor=true,
        setResolution=false,
        setViewport=false
    },
    internet={
        connect=false,
        isHttpEnabled=true,
        isTcpEnabled=true,
        request=false
    },
    modem={
        broadcast=false,
        close=false,
        getStrength=true,
        getWakeMessage=true,
        isOpen=true,
        isWired=true,
        isWireless=true,
        open=false,
        send=false,
        setStrength=false,
        setWakeMessage=false
    },
    screen={
        getAspectRatio=true,
        getKeyboards=false,
        isOn=true,
        isPrecise=true,
        isTouchModeInverted=true,
        setPrecise=false,
        setTouchModeInverted=false,
        turnOff=false,
        turnOn=false
    }
}

return methods